# Generated by Django 4.2.3 on 2026-01-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('avg_balance', models.CharField(max_length=50)),
                ('total_transactions', models.IntegerField()),
                ('flagged_transactions', models.IntegerField()),
                ('risk_history', models.JSONField(default=list)),
                ('counterparties', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('related_account', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activity', to='dashboard.account')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=20, unique=True)),
                ('risk_score', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('transactions_count', models.IntegerField()),
                ('priority', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.account')),
            ],
        ),
    ]
