# Generated by Django 4.2.3 on 2026-01-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_account_user_alert_user_processingtask_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('user', 'alert_id')},
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
