from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from .vector_store import VectorStoreManager
from django.conf import settings

class SARGenerator:
    def __init__(self, api_key):
        self.llm = ChatGroq(
            temperature=0.1,
            model_name="llama-3.3-70b-versatile", # updated supported model
            groq_api_key=api_key
        )
        self.vector_manager = VectorStoreManager()
        self.vector_db = self.vector_manager.load_vector_db()

    def generate_report(self, customer_data, patterns, risk_score, evidence):
        """Generates a professional, structured Deep Analysis Report using RAG and Groq."""
        
        # 1. Retrieve relevant laws from the Vector DB
        query = f"Money laundering laws related to {', '.join(patterns)} under PMLA 2002 and RBI KYC Master Directions"
        relevant_laws = ""
        if self.vector_db:
            try:
                docs = self.vector_db.similarity_search(query, k=5)
                # Add source metadata if available
                relevant_laws = "\n\n".join([f"Source: {doc.metadata.get('source', 'Unknown Document')}\nContent: {doc.page_content}" for doc in docs])
            except Exception as e:
                print(f"RAG Retrieval Error: {e}")
                relevant_laws = "Vector Database not accessible. Using general PMLA knowledge."
        
        # 2. Prepare the AI Prompt based on strict corporate requirements
        prompt = ChatPromptTemplate.from_messages([
            ("system", """You are an elite Financial Crime Compliance Officer at a major Indian Bank. 
            You are generating a formal Suspicious Activity Report (SAR) for the Financial Intelligence Unit (FIU-IND).
            
            Your task is to take the transaction evidence and risk factors, cross-reference them with the provided Regulatory Context (PMLA 2002, RBI Guidelines), and generate a legally precise report.
            
            FORMATTING RULES:
            - Use standard Markdown.
            - Use Markdown tables for data.
            - Be extremely concise and professional.
            - If the provided laws don't explicitly mention the pattern, infer from general Principles of PMLA (Section 3) or FATF Recommendations.
            """),
            ("user", """
            GENERATE A SAR REPORT IN THE EXACT FORMAT BELOW:

            # SUSPICIOUS ACTIVITY REPORT (SAR)
            **(Confidential - For Internal/Regulatory Use Only)**

            ---
            **RISK LEVEL: {risk_level}** (Score: {risk_score})
            ---

            ### 1. Report Information
            | Field | Details |
            |---|---|
            | **SAR ID** | {case_id} |
            | **Generated Date** | (Insert Current Date) |
            | **Account ID** | {acc_id} |
            | **Customer Name** | {name} |
            | **Risk Score** | {risk_score}/100 |

            ### 2. Detected Money Laundering Pattern
            **Primary Typology:** {patterns}
            
            ### 3. Transaction Summary
            (Analyze the provided evidence to fill this)
            | Metric | Value |
            |---|---|
            | **Transaction Count** | (Count from evidence, approx) |
            | **Total Volume** | (Sum from evidence, approx) |
            | **Suspicious Period** | (Date range from evidence) |

            ### 4. Violated AML Laws and Regulations
            (Based strictly on the RAG REGULATORY GUIDANCE provided below. If specific section unknown, cite 'PMLA Section 3 (Offence of Money Laundering)')

            | Law/Regulation | Section/Reference | Relevance Score (0-1) |
            |---|---|---|
            | (e.g. PMLA 2002) | (e.g. Section 3 / Section 12) | (0.95) |
            | (e.g. RBI KYC Master Direction) | (e.g. Section 58 - Monitoring) | (0.88) |
            
            ### 5. Compliance Narrative and Legal Analysis
            *Note: The following analysis is based on retrieved AML law provisions.*
            
            **Violated Laws Analysis:**
            (Explain clearly how the customer's behavior violates the specific sections cited above. Quote the law if possible from the context.)

            **Behavioral Reconstruction:**
            (Reconstruct the flow of funds using the transaction evidence. Use bullet points for clarity.)

            ### 6. Compliance Recommendation
            > **URGENT: File Suspicious Transaction Report (STR) with FIU-IND immediately.**
            > **Escalate to Senior Compliance Management.**
            > **Consider temporary account freeze pending Enhanced Due Diligence (EDD).**

            ---
            *This report is generated by an AI-assisted AML compliance system. All findings must be reviewed by qualified compliance officers before submission.*

            __________________________________________________________________________________
            
            ### INPUT DATA FOR ANALYSIS:
            
            **Transaction Evidence:**
            {evidence}

            **Detected Patterns:**
            {patterns}

            **RAG REGULATORY GUIDANCE (SOURCE MATERIAL):**
            {laws}
            """)
        ])

        # 3. Generate the response
        chain = prompt | self.llm
        
        # Determine risk level string
        score = int(risk_score)
        risk_level = "CRITICAL - IMMEDIATE ACTION REQUIRED" if score >= 90 else "HIGH PRIORITY - INVESTIGATE" if score >= 75 else "MEDIUM RISK"

        response = chain.invoke({
            "name": customer_data.get('name', 'Unknown'),
            "acc_id": customer_data.get('account_id', 'Unknown'),
            "case_id": customer_data.get('case_id', 'SAR-GEN-001'),
            "risk_score": risk_score,
            "risk_level": risk_level,
            "patterns": ", ".join(patterns),
            "evidence": evidence,
            "laws": relevant_laws if relevant_laws else "General PMLA 2002 and RBI KYC Master Directions apply."
        })

        return response.content
